// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDef3V1G7ghhvRTZQVgOd4x7X_gMADsBj4',
    appId: '1:957227247284:web:40f71313581558d33459e1',
    messagingSenderId: '957227247284',
    projectId: 'expenseapp-15e0a',
    authDomain: 'expenseapp-15e0a.firebaseapp.com',
    storageBucket: 'expenseapp-15e0a.firebasestorage.app',
    measurementId: 'G-CV5SDPGFQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAwMK2d_shwS9-gNHPYlMXAiUbpW8qfac',
    appId: '1:957227247284:android:54480b63e80bacd93459e1',
    messagingSenderId: '957227247284',
    projectId: 'expenseapp-15e0a',
    storageBucket: 'expenseapp-15e0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBfbMMVIicY6I_lRjPZmERn64wQqF2n3c',
    appId: '1:957227247284:ios:a5ea426ec6e7e7463459e1',
    messagingSenderId: '957227247284',
    projectId: 'expenseapp-15e0a',
    storageBucket: 'expenseapp-15e0a.firebasestorage.app',
    iosBundleId: 'com.example.expnesetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBfbMMVIicY6I_lRjPZmERn64wQqF2n3c',
    appId: '1:957227247284:ios:a5ea426ec6e7e7463459e1',
    messagingSenderId: '957227247284',
    projectId: 'expenseapp-15e0a',
    storageBucket: 'expenseapp-15e0a.firebasestorage.app',
    iosBundleId: 'com.example.expnesetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDef3V1G7ghhvRTZQVgOd4x7X_gMADsBj4',
    appId: '1:957227247284:web:d0fe0c94fbe866143459e1',
    messagingSenderId: '957227247284',
    projectId: 'expenseapp-15e0a',
    authDomain: 'expenseapp-15e0a.firebaseapp.com',
    storageBucket: 'expenseapp-15e0a.firebasestorage.app',
    measurementId: 'G-537G4CNDXW',
  );
}
